### PR TITLE
Add quotes to template

### PR DESCRIPTION
**Pull request by robbiecarlton**
currently chaperone-server config currently requires quotes in its string arguments
eg
`{
  path: '"/"',
  host: '"http://whatever.com"'
}`

This fixes this so that you can just pass in the value

`{
  path: '/',
  host: 'http://whatever.com'
}`

This has been bugging me and I don't see a reason not to make this change, but curious if anyone objects.

Edit - And while we're breaking peoples configs, `connection.address` is now `connection.host`, to match the field name in `chaperone`.

### CODE REVIEW

**Comment by timotree3** [comment]
Makes sense to me. I tried this at one point and it didn't work but perhaps I just did it wrong

**Comment by robbiecarlton** [comment]
@timotree3 - I made another change since you looked, if you want to look at that one too

**Review by zo-el — COMMENTED** [review]
Looks fine. But we need to update all the repos where chaperone is a dependency or used for testing.
Let's have those repos ready and tested before we get this merged since this repo is under constant bug fix and updates for manual testing.

**Comment by robbiecarlton** [comment]
@zo-el - that's only once we create a release right? We can merge this to develop and not update the other repos til we make a new chaperone release

**Comment by zo-el** [comment]
Merging it to develop deploys it on the `chaperone-dev` server and if we then use that for testing things would start breaking.
So because of the quick testing rounds, we should get the other repos updated quickly. 

I am not blocking this PR, but just wanting us to track that we can't let updating the other repos for too long

**Comment by timotree3** [comment]
This only affects situations that use `bin/html/index.html`, which does not include any kind of deployment like to `chaperone-dev`. Those all use `src/static/index.html`

**Review by zo-el — APPROVED** [review]

**Pull request merged**
